/**
 * This program and the accompanying materials
 * are made available under the terms of the License
 * which accompanies this distribution in the file LICENSE.txt
 */
package com.archimatetool.export.svg;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;

import org.apache.batik.dom.GenericDocument;
import org.apache.batik.svggen.SVGGeneratorContext;
import org.eclipse.draw2d.Figure;
import org.eclipse.draw2d.FreeformLayer;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.geometry.Rectangle;
import org.eclipse.swt.widgets.Shell;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Document;


@SuppressWarnings("nls")
public abstract class AbstractExportProviderTests {
    
    protected Shell shell;
    protected IFigure rootFigure;
    
    @BeforeEach
    public void runOnceBeforeEachTest() {
        shell = new Shell();
        rootFigure = new FreeformLayer();
        rootFigure.setBounds(new Rectangle(0, 0, 500, 500));
    }
    
    @AfterEach
    public void runOnceAfterEachTest() {
        shell.dispose();
    }
    
    protected abstract AbstractExportProvider getProvider();

    @Test
    public void testGetViewportBounds() {
        getProvider().init(null, shell, rootFigure);

        // Default blank size
        assertEquals(new Rectangle(0, 0, 100, 100), getProvider().getViewportBounds(rootFigure));
        
        // Add a child figure
        IFigure childFigure = new Figure();
        rootFigure.add(childFigure);

        // Bounds is expanded by 10 pixesls each side
        childFigure.setBounds(new Rectangle(0, 0, 100, 50));
        assertEquals(new Rectangle(-10, -10, 120, 70), getProvider().getViewportBounds(rootFigure));
        
        // Bounds is small figure and expanded by 10 pixesls each side
        childFigure.setBounds(new Rectangle(200, 200, 128, 52));
        assertEquals(new Rectangle(190, 190, 148, 72), getProvider().getViewportBounds(rootFigure));
    }

    @Test
    public void testCreateDocument() {
        Document document = getProvider().createDocument();
        assertNotNull(document);
        assertNotNull(document.getDocumentElement());
    }
    
    @Test
    public void testCreateContext() {
        getProvider().init(null, shell, rootFigure);
        SVGGeneratorContext ctx = getProvider().createContext(new GenericDocument(null, null), true);
        assertNotNull(ctx);
        assertTrue(ctx.isEmbeddedFontsOn());
        assertTrue(ctx.getComment().startsWith("Generated by Archi"));
    }
    
    @Test
    public void testSetViewBoxAttribute() {
        Document document = getProvider().createDocument();
        getProvider().setViewBoxAttribute(document.getDocumentElement(), 12, 13, 14, 15);
        assertEquals("12 13 14 15", document.getDocumentElement().getAttribute("viewBox"));
    }
    
    @Test
    public void testSetSizeAttributes() {
        Document document = getProvider().createDocument();
        getProvider().setSizeAttributes(document.getDocumentElement(), 100, 200);
        assertEquals("100", document.getDocumentElement().getAttribute("width"));
        assertEquals("200", document.getDocumentElement().getAttribute("height"));
    }
    
    @Test
    public void testGetSVGString() throws IOException {
        getProvider().setFigure(rootFigure);
        getProvider().initialiseGraphics();
        String s = getProvider().getSVGString(getProvider().svgGraphics2D.getRoot());
        assertTrue(s.startsWith("<?xml version=\"1.0\"?>"));
    }
}
