name: 🐞 Bug Report 
description: Report a bug in Archi
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: input
    id: version
    attributes:
      label: Archi Version
      description: Which version of Archi are you using?
      placeholder: ex. 5.6.0
    validations:
      required: true
  - type: input
    id: os-kind
    attributes:
      label: Operating System
      description: Which operating system and version are you using?
      placeholder: ex. Windows 11, macOS 15, Ubuntu 25.04
    validations:
      required: true
  - type: input
    id: archi-plugins
    attributes:
      label: Archi Plug-ins
      description: | 
        If you are using additional Archi Plugins please list them
      placeholder: |
        ex: jArchi 1.10, coArchi 0.9.4, None
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.

        Attach the Archi error log if possible. This can be accessed in Archi by selecting the "About Archi" menu item. In the dialog box press the "Installation Details" button, then select the "Configuration" tab and press the "View Error Log" button.
        
        If you able to attach an *.archimate file that demonstrates the problem, please also attach that. 
      placeholder: |
        Please enter a description of the issue. You can also attach screenshots, log files and an example *.archimate file (in a zip file)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: false
