bin.includes = META-INF/,\
               LICENSE.txt,\
               com.archimatetool.markdown.jar,\
               commonmark-0.28.0.jar,\
               commonmark-ext-gfm-tables-0.28.0.jar,\
               commonmark-ext-gfm-strikethrough-0.28.0.jar,\
               commonmark-ext-ins-0.28.0.jar,\
               wrapper.html,\
               commonmark-ext-autolink-0.28.0.jar,\
               autolink-0.12.0.jar
jars.compile.order = com.archimatetool.markdown.jar
source.com.archimatetool.markdown.jar = src/
output.com.archimatetool.markdown.jar = bin/
