bin.includes = META-INF/,\
               LICENSE.txt,\
               com.archimatetool.markdown.jar,\
               wrapper.html,\
               lib/
jars.compile.order = com.archimatetool.markdown.jar
source.com.archimatetool.markdown.jar = src/
output.com.archimatetool.markdown.jar = bin/
